export const GET_CONTENTS = "GET_CONTENTS";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const ADD_CONTENT = "ADD_CONTENT";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGES";
