# Generated by Django 3.0.6 on 2020-06-01 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from accounts.models import CustomUser

class Migration(migrations.Migration):

    def seed_data(apps, schema_editor):
        user = CustomUser(username='admin',
                            email='admin@admin.com',
                            is_staff=True,
                            is_superuser=True)
        user.set_password('qwertyuiop')
        user.save()
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUserContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_data)
    ]
